version = 0.1

[default.deploy.parameters]
stack_name = "disastertech-backend"
resolve_s3 = true
s3_prefix = "disastertech-backend"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "SesFromAddress=\"azaynul3@gmail.com\" SesToAddress=\"azaynul3@gmail.com\""
image_repositories = []
